package com.bugbuddy.repository;

import com.bugbuddy.entity.Bug;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * Spring Data JPA repository for the {@link Bug} entity.
 *
 * ──────────────────────────────────────────────────────────────────────────
 * FULLTEXT INDEX PRE-REQUISITE (run once after first app startup):
 *
 *   ALTER TABLE bugs
 *     ADD FULLTEXT INDEX ft_bug_search (error_text, ai_explanation);
 *
 * This index is NOT auto-generated by Hibernate DDL (ddl-auto=update does not
 * create FULLTEXT indexes). The native @Query below uses MATCH...AGAINST which
 * requires this index to exist for correct (and performant) results.
 * ──────────────────────────────────────────────────────────────────────────
 */
@Repository
public interface BugRepository extends JpaRepository<Bug, Long> {

    /**
     * Exact-match lookup by the trimmed error text.
     * Used by BugService to detect cache hits before invoking the AI.
     *
     * @param errorText the raw error string to match
     * @return an Optional containing the cached Bug if found
     */
    Optional<Bug> findByErrorText(String errorText);

    /**
     * MySQL FULLTEXT search across error_text and ai_explanation columns.
     *
     * Uses MATCH...AGAINST in natural language mode — the most relevant
     * results are returned first (ordered by relevance score DESC).
     *
     * The {nativeQuery = true} flag is mandatory; MATCH...AGAINST is
     * MySQL-specific syntax and cannot be expressed in JPQL.
     *
     * @param keyword  the search term(s) — passed directly to AGAINST()
     * @return list of matching Bug records ordered by relevance
     */
    @Query(
        value = """
            SELECT *
            FROM bugs
            WHERE MATCH(error_text, ai_explanation) AGAINST (:keyword IN NATURAL LANGUAGE MODE)
            ORDER BY MATCH(error_text, ai_explanation) AGAINST (:keyword IN NATURAL LANGUAGE MODE) DESC
            """,
        nativeQuery = true
    )
    List<Bug> fullTextSearch(@Param("keyword") String keyword);

    /**
     * Find all bugs for a given programming language, ordered newest-first.
     * Useful for future language-specific filtering endpoints.
     *
     * @param language e.g. "Java", "Python", "JavaScript"
     * @return list of matching Bug records
     */
    List<Bug> findByLanguageIgnoreCaseOrderByCreatedAtDesc(String language);
}
